#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap           5
bscp config top_padding          5
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true


bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

# Auto-inicio
polybar -c /home/wellington/.config/polybar/config.ini &
xsetroot -cursor_name left_ptr
exec /home/wellington/.fehbg
